"""The generated wiki index, per-operation catalogs and frontmatter edits.

Pure functions over the page mapping that link_check.collect() returns
(canonical path -> {"metadata", "body"}); nothing here reads or writes files.

build_index(pages)  the whole wiki/index.md, derived from each content page's
                    title, summary, theme, gaps and part_of. Deterministic, so
                    the checker can report an index that no longer matches.
catalog(pages, ...) a size-bounded selection of the index for one operation.
set_fields(text, …) change frontmatter keys of one page.
duplicates(...)     new pages whose title or alias matches an existing page.
Standard library only.
"""

import json
import math
import re


MARKER = ("<!-- Generated by the operator from page frontmatter (summary, theme, gaps, part_of). "
          "Do not edit: change the pages and the operator regenerates this file. -->")
CONTROLS = ("wiki/index.md", "wiki/log.md")
SECTIONS = (("Concepts", "concept"), ("Entities", "entity"), ("Synthesis", "synthesis"), ("Sources", "source"))
FOLDER_TYPE = {"sources": "source", "concepts": "concept", "entities": "entity", "synthesis": "synthesis"}
LINK = re.compile(r"\[\[([^\]|#]+)")
WORD = re.compile(r"[a-z0-9][a-z0-9+#.-]*[a-z0-9+#]|[a-z0-9]")
STOP = set("""a an and are as at be by for from has have how in into is it its of on or that the this to was
were what when which with without vs via not no new can use using your you their they them these those than
then there over under about after before between more most other also only per each part parts page pages""".split())
SUMMARY_MAX = 300


def natural_key(text):
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", text)]


def is_generated(text):
    return MARKER in text


def label(text):
    """A title usable inside [[path|label]]."""
    return re.sub(r"\s+", " ", re.sub(r"[|\[\]]", " ", text)).strip()


def page_type(key):
    parts = key.split("/")
    return FOLDER_TYPE.get(parts[1]) if len(parts) > 2 and parts[0] == "wiki" else None


def text_field(meta, key):
    value = meta.get(key)
    return value.strip() if isinstance(value, str) and value.strip() else None


def records(pages):
    """One record per content page, keyed by extensionless path."""
    found = {}
    for key, page in pages.items():
        if key in CONTROLS or not key.endswith(".md") or not page_type(key):
            continue
        meta = page.get("metadata") or {}
        gaps = meta.get("gaps")
        found[key[:-3]] = {
            "path": key[:-3], "type": page_type(key),
            "title": label(text_field(meta, "title") or key[:-3].rsplit("/", 1)[-1]),
            "summary": re.sub(r"\s+", " ", text_field(meta, "summary") or "") or None,
            "theme": label(text_field(meta, "theme") or "") or None,
            "gaps": [re.sub(r"\s+", " ", g).strip() for g in gaps if isinstance(g, str) and g.strip()]
            if isinstance(gaps, list) else [],
            "part_of": text_field(meta, "part_of"),
            "aliases": [a for a in meta.get("aliases") or [] if isinstance(a, str)],
            "tags": [t for t in meta.get("tags") or [] if isinstance(t, str)],
            "updated": text_field(meta, "updated"), "created": text_field(meta, "created"),
            "links": {target.strip() for target in LINK.findall(page.get("body") or "")},
        }
    return found


def parents(found):
    """{part: chapter} for every part_of that names an existing page which links back to the part."""
    return {path: info["part_of"] for path, info in found.items()
            if info["part_of"] and info["part_of"] != path and info["part_of"] in found
            and path in found[info["part_of"]]["links"]}


def entry_line(info, parts=0):
    line = f"- [[{info['path']}|{info['title']}]]"
    if info["summary"]:
        line += f" — {info['summary']}"
    if parts:
        line += f" ({parts} part{'s' if parts != 1 else ''})"
    return line


def grouped(items):
    """[(theme or None, items)] with unthemed first, themes and items in natural order."""
    by_theme = {}
    for info in items:
        by_theme.setdefault(info["theme"], []).append(info)
    order = sorted(by_theme, key=lambda theme: (theme is not None, natural_key(theme or "")))
    return [(theme, sorted(by_theme[theme], key=lambda i: (natural_key(i["title"]), i["path"]))) for theme in order]


def build_index(pages, created=None):
    """The complete text of wiki/index.md for these pages."""
    found = records(pages)
    part_of = parents(found)
    counts = {}
    for chapter in part_of.values():
        counts[chapter] = counts.get(chapter, 0) + 1
    dates = sorted(d for info in found.values() for d in (info["updated"], info["created"])
                   if d and re.fullmatch(r"\d{4}-\d{2}-\d{2}", d))
    created = created or (dates[0] if dates else "1970-01-01")
    updated = max(dates[-1], created) if dates else created
    lines = ["---", 'title: "Index"', 'type: "index"', f"created: {json.dumps(created)}",
             f"updated: {json.dumps(updated)}", "aliases: []", "tags: []", "---", "", "# Index", "", MARKER, ""]
    for section, kind in SECTIONS:
        lines += [f"## {section}", ""]
        items = [info for info in found.values() if info["type"] == kind and info["path"] not in part_of]
        if not items:
            lines += ["No pages yet.", ""]
            continue
        for theme, members in grouped(items):
            if theme:
                lines += [f"### {theme}", ""]
            lines += [entry_line(info, counts.get(info["path"], 0)) for info in members] + [""]
    lines += ["## Gaps", ""]
    gapped = [info for info in found.values() if info["gaps"]]
    if not gapped:
        lines += ["No known gaps yet.", ""]
    for theme, members in grouped(gapped):
        if theme:
            lines += [f"### {theme}", ""]
        lines += [f"- [[{info['path']}|{info['title']}]]: {gap}" for info in members for gap in info["gaps"]] + [""]
    return "\n".join(lines).rstrip("\n") + "\n"


def terms(text):
    return {word for word in WORD.findall((text or "").lower()) if word not in STOP and len(word) > 2}


def rank(found, query, bodies=None):
    """Pages scored against the query terms: title, aliases, tags and theme weigh 3, the summary 1, and
    the body (when `bodies` maps paths to text) 0.5."""
    wanted = terms(query)
    if not wanted:
        return []
    names = {path: terms(" ".join([info["title"], *info["aliases"], *info["tags"], info["theme"] or "",
                                   path.rsplit("/", 1)[-1].replace("-", " ")]))
             for path, info in found.items()}
    summaries = {path: terms(info["summary"]) for path, info in found.items()}
    text = {path: terms((bodies or {}).get(path, "")) & wanted for path in found}
    total = len(found) or 1
    weight = {word: math.log(1 + total / (1 + sum(word in names[p] or word in summaries[p] or word in text[p]
                                                    for p in found)))
              for word in wanted}
    scored = []
    for path in found:
        score = sum(weight[w] * (3 if w in names[path] else 1 if w in summaries[path] else 0.5 if w in text[path]
                                 else 0) for w in wanted)
        if score > 0:
            scored.append((-score, natural_key(found[path]["title"]), path))
    return [path for _, _, path in sorted(scored)]


def catalog(pages, inputs=(), task="", budget=24_000):
    """A bounded catalog for one operation, most relevant first; the rest is found by search.

    Order: the inputs' neighbours (pages they link or that link them, their chapter and parts),
    pages sharing an input's theme, the best matches for the task, then the remaining concept,
    entity and synthesis titles, and the remaining themes with their page counts.
    """
    found = records(pages)
    inputs = [path[:-3] if path.endswith(".md") else path for path in inputs]
    part_of = parents(found)
    chosen, shown = [], set()

    def take(paths):
        for path in paths:
            if path in found and path not in shown and path not in inputs:
                shown.add(path)
                chosen.append(path)

    linked = []
    for path in inputs:
        if path in found:
            linked += sorted(found[path]["links"])
            linked += sorted((p for p, info in found.items() if path in info["links"]), key=natural_key)
            linked += [found[path]["part_of"]] if found[path]["part_of"] else []
    take(linked)
    themes = {found[p]["theme"] for p in inputs if p in found and found[p]["theme"]}
    take(sorted((p for p, info in found.items() if info["theme"] in themes and p not in part_of),
                key=lambda p: natural_key(found[p]["title"])))
    query = " ".join([task, *(found[p]["title"] + " " + (found[p]["summary"] or "") for p in inputs if p in found)])
    take(rank(found, query, {key[:-3]: page.get("body") or "" for key, page in pages.items()})[:60])
    head = ["# Catalog for this operation", "",
            f"The wiki has {len(found)} pages. This catalog lists the ones most likely to matter here, with "
            "their one-line summaries, then the remaining concept, entity and synthesis titles. It is not "
            "the whole wiki: search wiki/ with grep or glob for anything else, and read a page completely "
            "before relying on it.", ""]
    body, size = [], sum(len(line) + 1 for line in head)
    omitted = 0

    def add(line):
        nonlocal size, omitted
        if size + len(line) + 1 > budget:
            omitted += 1
            return False
        body.append(line)
        size += len(line) + 1
        return True

    if inputs:
        add("## Inputs")
        add("")
        for path in inputs:
            add(f"- {path}.md" + (f" — {found[path]['title']}" if path in found else ""))
        add("")
    if chosen:
        add("## Related pages")
        add("")
        for path in chosen:
            info = found[path]
            add(entry_line(info) + f" ({info['type']}" + (f"; {info['theme']}" if info["theme"] else "")
                + (f"; part of [[{info['part_of']}]]" if path in part_of else "") + ")")
        add("")
    rest = [info for info in found.values() if info["type"] != "source" and info["path"] not in shown
            and info["path"] not in inputs]
    if rest:
        add("## Other concepts, entities and synthesis")
        add("")
        for info in sorted(rest, key=lambda i: (i["type"], natural_key(i["title"]))):
            add(f"- [[{info['path']}|{info['title']}]] ({info['type']})")
        add("")
    counts = {}
    for path, info in found.items():
        if info["type"] == "source" and path not in shown and path not in inputs:
            counts[info["theme"] or "(no theme)"] = counts.get(info["theme"] or "(no theme)", 0) + 1
    if counts:
        add("## Other sources, by theme")
        add("")
        for theme in sorted(counts, key=natural_key):
            add(f"- {theme}: {counts[theme]} source page{'s' if counts[theme] != 1 else ''}")
        add("")
    if omitted:
        body.append(f"({omitted} further lines omitted to keep this catalog readable in one pass; search wiki/.)")
    return "\n".join(head + body).rstrip("\n") + "\n"


def split_frontmatter(text):
    """(frontmatter lines without the --- fences, body) or (None, text) when there is none."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return None, text
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return None, text
    return lines[1:end], "\n".join(lines[end + 1:])


def get_field(text, key):
    fields, _ = split_frontmatter(text)
    for line in fields or []:
        if line.startswith(f"{key}: "):
            try:
                return json.loads(line[len(key) + 2:])
            except ValueError:
                return None
    return None


def has_field(text, key):
    fields, _ = split_frontmatter(text)
    return any(line.startswith(f"{key}: ") for line in fields or [])


def set_fields(text, values):
    """Set frontmatter keys to JSON values, in place or appended before the closing fence."""
    fields, body = split_frontmatter(text)
    if fields is None:
        raise ValueError("page has no frontmatter")
    for key, value in values.items():
        line = f"{key}: {json.dumps(value, ensure_ascii=False)}"
        position = next((i for i, existing in enumerate(fields) if existing.startswith(f"{key}: ")), None)
        if position is None:
            fields.append(line)
        else:
            fields[position] = line
    return "\n".join(["---", *fields, "---"]) + "\n" + body


def first_sentence(body, limit=200):
    """A fallback summary: the first sentence of the first prose paragraph."""
    fence = False
    for raw in body.splitlines():
        line = raw.strip()
        if line.startswith(("```", "~~~")):
            fence = not fence
            continue
        if fence or not line or line.startswith(("#", "<!--", "-", "*", "|", ">", "!", "<")):
            continue
        line = re.sub(r"\[\[[^\]|]+\|([^\]]+)\]\]", r"\1", line)
        line = re.sub(r"\[\[([^\]]+)\]\]", lambda m: m.group(1).rsplit("/", 1)[-1], line)
        line = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", line)
        line = re.sub(r"[*_`]", "", line)
        sentence = re.split(r"(?<=[.!?])\s", line, maxsplit=1)[0].strip()
        if len(sentence) > limit:
            sentence = sentence[:limit - 1].rsplit(" ", 1)[0] + "…"
        return sentence
    return None


def normalized(text):
    return re.sub(r"[^a-z0-9]+", " ", (text or "").lower()).strip()


def names(info):
    values = [info["title"], *info["aliases"]]
    return {normalized(v) for v in values if len(normalized(v)) >= 4}


COMPARABLE = {"source": {"source"}, "concept": {"concept", "entity"}, "entity": {"concept", "entity"},
              "synthesis": {"synthesis"}}


def duplicates(pages, new_pages):
    """[(new path, existing path, name)] where a new page's title or alias names an existing page.

    pages: the vault's pages; new_pages: {key.md: page} for pages the proposal creates. Only pages of
    comparable types collide (a concept and an entity can, a concept and a source cannot).
    """
    existing = records(pages)
    fresh = records(new_pages)
    found = []
    for path, info in sorted(fresh.items()):
        for other, known in sorted(existing.items()):
            if other == path or known["type"] not in COMPARABLE[info["type"]]:
                continue
            slug = normalized(other.rsplit("/", 1)[-1].replace("-", " "))
            hit = names(info) & (names(known) | ({slug} if len(slug) >= 4 else set()))
            if hit:
                found.append((path, other, sorted(hit)[0]))
                break
    return found
